export const FORM_FIELD_IDS = {
  trackId: "entry.1012427879",
  trackName: "entry.1201510822",
  artistName: "entry.842038551",
  albumName: "entry.2136618658",
  artworkUrl: "entry.1913993909",
  previewUrl: "entry.729930720",
  requesterName: "entry.924392852",
  dedication: "entry.1792970976",
  contact: "entry.40872869",
} as const;

export type FormFieldIds = typeof FORM_FIELD_IDS;

/**
 * Update the placeholder entry IDs above to match the IDs generated by your Google Form.
 * You can capture them from the pre-filled URL (look for `entry.xxxxx` query parameters).
 */
